spring:
  datasource:
    url: jdbc:postgresql://dpg-d1655ljipnbc73fiqvs0-a.oregon-postgres.render.com:5432/applimp
    username: applimp_user
    password: YsnPsopBf57q1rfJvrFt5DLsyW0ve0nO
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080
